services:
  
  poc.api:
    image: opentelemetry.poc.api
    container_name: api
    build:
      context: .
      dockerfile: src/OpenTelemetry.POC.Api/Dockerfile
    ports:
      - "54203:80"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
    env_file:
      - ./poc.env
    depends_on:
      localstack:
        condition: service_healthy
      postgres:
        condition: service_healthy
  
  poc.consumer:
    image: opentelemetry.poc.consumer
    container_name: consumer
    build:
      context: .
      dockerfile: src/OpenTelemetry.POC.Consumer/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
    env_file:
      - ./poc.env
    depends_on:
      localstack:
        condition: service_healthy
  
  postgres:
    image: postgres
    container_name: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB:-OT_POC}", "-U", "${POSTGRES_USER:-debug}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-OT_POC}
      POSTGRES_USER: ${POSTGRES_USER:-debug}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-debug}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
    ports:
      - "5432:5432"

  localstack:
    image: localstack/localstack
    container_name: localstack
    healthcheck:
      test: awslocal sns list-topics && awslocal sqs list-queues
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    ports:
      - "4566:4566"
    environment:
      SERVICES: sns,sqs
  
  zipkin-server:
    image: openzipkin/zipkin:latest
    container_name: zipkin-server
    restart: always
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    container_name: otlp-colector
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "55679:55679" # zpages extension