receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins: 
          - http://*

exporters:
  
  #prometheus:
  #  endpoint: "0.0.0.0:8889"
  #  const_labels:
  #    label1: value1
  
  #zipkin:
  #  endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
  #  format: proto

  logging:
    loglevel: info
  
  otlp/elastic:
    endpoint: apm-server:8200
    tls:
      insecure: true
  
  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  
  pipelines:
    
    logs:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]
      
    metrics:
      receivers: [ otlp ]
      exporters: [ logging, otlp/elastic ]
      
    traces:
      receivers: [otlp]
      exporters: [jaeger, otlp/elastic]